[package]
name = "lang_macro"
version = "0.1.0"
edition = "2018"

[lib]
name = "lang_macro"
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "1.0", features = ["parsing", "full", "extra-traits"] }
proc-macro2 = "1"
